name: Testing

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron:  '0 0 * * *' # Run every day.

jobs:
  test:
    uses: wp-cli/.github/.github/workflows/reusable-testing.yml@main
